services:
    vouchedfor_consent:
      class: VouchedFor\ConsentBundle\Services\ConsentHandler
      public: true
      arguments:
          $dynamoDbClient: '@aws.dynamodb'
          $tableName: '%vouchedfor_consent.table_name%'
          $password: '%vouchedfor_consent.password%'