services:
    vouchedfor_consent:
      class: VouchedFor\ConsentBundle\Services\ConsentHandler
      arguments:
          $dynamoDbClient: '@aws.dynamodb'
          $tableName: '%vouchedfor_consent.table_name%'